name: CI/CD 3-Tier App on EKS

on:
  push:
    branches: [ "main" ]  # triggers on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # ----------------- Step 1: Checkout Repo -----------------
    - name: Checkout source code
      uses: actions/checkout@v4

    # ----------------- Step 2: Configure AWS -----------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # ----------------- Step 3: Login to Amazon ECR -----------------
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # ----------------- Step 4: Build and Push Backend Image -----------------
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./TWSThreeTierAppChallenge/Application-Code/backend
        file: ./TWSThreeTierAppChallenge/Application-Code/backend/Dockerfile
        push: true
        tags: |
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend:latest

    # ----------------- Step 5: Build and Push Frontend Image -----------------
    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./TWSThreeTierAppChallenge/Application-Code/frontend
        file: ./TWSThreeTierAppChallenge/Application-Code/frontend/Dockerfile
        push: true
        tags: |
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend:latest

    # ----------------- Step 6: Configure kubectl for EKS -----------------
    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
        export KUBECONFIG=kubeconfig

    # ----------------- Step 7: Deploy Backend -----------------
    - name: Deploy backend to EKS
      run: |
        kubectl apply -f TWSThreeTierAppChallenge/Kubernetes-Manifests-file/Backend

    # ----------------- Step 8: Deploy Frontend -----------------
    - name: Deploy frontend to EKS
      run: |
        kubectl apply -f TWSThreeTierAppChallenge/Kubernetes-Manifests-file/Frontend

    # ----------------- Step 9: Deploy Database -----------------
    - name: Deploy database to EKS
      run: |
        kubectl apply -f TWSThreeTierAppChallenge/Kubernetes-Manifests-file/Database

    # ----------------- Step 10: Deploy Ingress -----------------
    - name: Deploy ingress
      run: |
        kubectl apply -f TWSThreeTierAppChallenge/Kubernetes-Manifests-file/ingress.yaml
